name: Annea Backend service Unit Test
on:
  pull_request:
    types: [opened, edited, reopened]
  push:

# Job Definition
jobs:
    Pre-build:
     runs-on: ubuntu-latest
     
     strategy:
       matrix:
         node-version: [20.x]
         
     steps:
     - name: Checkout step
       uses: actions/checkout@v4
     - uses: nelonoel/branch-name@v1.0.1
     - name: Use node ${{matrix.node-version}}
       uses: actions/setup-node@v3
     - name: Install project dependencies
       run: npm ci
     - name: Run unit tests
       run: npm run test